openapi: 3.0.1
info:
  contact:
    name: "Stefan Wagenpfeil, Patrick Steinert"
  description: GMAF REST
  title: GMAF
  version: 1.1.0
servers:
- url: http://85.215.58.111:8242/gmaf/gmafApi/gmaf/
paths:
  /gmaf/getToken/{api-key}:
    get:
      operationId: getAuthToken
      parameters:
      - explode: false
        in: path
        name: api-key
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            '*/*':
              schema:
                type: string
          description: default response
      x-accepts: '*/*'
  /gmaf/getCollection/{auth-token}:
    post:
      operationId: getCollection
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MMFG'
                type: array
          description: default response
      x-accepts: application/json
  /gmaf/get-collection-ids/{auth-token}:
    post:
      operationId: getCollectionIds
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: default response
      x-accepts: application/json
  /gmaf/getMetadata/{auth-token}:
    post:
      operationId: getCollectionMetadata
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GeneralMetadata'
                type: array
          description: default response
      x-accepts: application/json
  /gmaf/preview/{auth-token}/{id}:
    get:
      operationId: getImage
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            image/*: {}
          description: default response
      x-accepts: image/*
    post:
      operationId: getPreviewURL
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                type: string
          description: default response
      x-accepts: application/json
  /gmaf/getmmfg/{auth-token}/{mmfg-id}:
    post:
      operationId: getMMFGForId
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: mmfg-id
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MMFG'
          description: default response
      x-accepts: application/json
  /gmaf/getgc/{auth-token}/{mmfg_id}:
    post:
      operationId: getOrGenerateGraphCode
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: mmfg_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                type: string
          description: default response
      x-accepts: application/json
  /gmaf/getRec/{auth-token}/{id}:
    post:
      operationId: getRecommendedAssets
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MMFG'
                type: array
          description: default response
      x-accepts: application/json
  /gmaf/{session}/{api-key}:
    post:
      operationId: getSession
      parameters:
      - explode: false
        in: path
        name: session
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: api-key
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GMAF'
          description: default response
      x-accepts: application/json
  /gmaf/getsimilarassetsbygraphcode/{auth-token}:
    post:
      operationId: getSimilarAssetIDsByGraphCode
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          '*/*':
            schema:
              type: string
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: default response
      x-content-type: '*/*'
      x-accepts: application/json
  /gmaf/getSim/{auth-token}/{id}:
    post:
      operationId: getSimilarAssets
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MMFG'
                type: array
          description: default response
      x-accepts: application/json
  /gmaf/query/{auth-token}/{query}:
    post:
      operationId: queryByKeyword
      parameters:
      - explode: false
        in: path
        name: auth-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: query
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: default response
      x-accepts: application/json
  /api:
    get:
      operationId: setProcessingPlugins
      responses:
        default:
          content:
            application/json: {}
          description: default response
      x-accepts: application/json
  /api/getAuthToken:
    get:
      operationId: getAuthToken_1
      responses:
        default:
          content:
            application/json:
              schema:
                type: string
          description: default response
      x-accepts: application/json
  /application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
      - explode: false
        in: path
        name: path
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/xml: {}
          description: default response
      x-accepts: application/xml
  /application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
          description: default response
      x-accepts: "application/vnd.sun.wadl+xml,application/xml"
components:
  schemas:
    AssetLink:
      example:
        assetName: assetName
        location: http://example.com/aeiou
        type: 7
      properties:
        type:
          format: int32
          type: integer
        location:
          format: url
          type: string
        assetName:
          type: string
      type: object
    CompositionRelationship:
      example:
        relatedObject: null
        type: 6
      properties:
        type:
          format: int32
          type: integer
        relatedObject:
          $ref: '#/components/schemas/Node'
      type: object
    Context:
      example:
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        name:
          type: string
        id:
          format: uuid
          type: string
      type: object
    GeneralMetadata:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        fileName: fileName
        cityNearBy: cityNearBy
        previewUrl: http://example.com/aeiou
        iso: 3
        sourceSystem: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        latitude: 4
        resolution: 6
        shutterSpeed: 6
        aperture: 5.025005
        exposure: 9.965781
        fileSize: 6
        cameraModel: cameraModel
        width: 8
        lensModel: lensModel
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        fileReference: ""
        longitude: 1
        focalLength: 9
        height: 9
      properties:
        id:
          format: uuid
          type: string
        longitude:
          format: int64
          type: integer
        latitude:
          format: int64
          type: integer
        cameraModel:
          type: string
        lensModel:
          type: string
        aperture:
          format: float
          type: number
        exposure:
          format: float
          type: number
        cityNearBy:
          type: string
        focalLength:
          format: int64
          type: integer
        resolution:
          format: int32
          type: integer
        width:
          format: int32
          type: integer
        height:
          format: int32
          type: integer
        date:
          format: date-time
          type: string
        fileSize:
          format: int64
          type: integer
        iso:
          format: int32
          type: integer
        shutterSpeed:
          format: int64
          type: integer
        fileName:
          type: string
        fileReference:
          format: binary
          type: string
        previewUrl:
          format: url
          type: string
        sourceSystem:
          format: uuid
          type: string
      type: object
    Location:
      example:
        name: name
        location: http://example.com/aeiou
        type: 1
      properties:
        type:
          format: int32
          type: integer
        location:
          format: url
          type: string
        name:
          type: string
      type: object
    MMFG:
      example:
        security:
          group_id: group_id
          owner_id: owner_id
          acl: acl
        nodes:
        - semanticRelationships:
          - relatedNode: http://example.com/aeiou
            description: description
          - relatedNode: http://example.com/aeiou
            description: description
          timerange:
            relativeTime: true
            universalTime: true
            end: 2000-01-23T04:56:07.000+00:00
            begin: 2000-01-23T04:56:07.000+00:00
          featureVector: null
          detectedBy: detectedBy
          name: name
          compositionRelationships:
          - relatedObject: null
            type: 6
          - relatedObject: null
            type: 6
          assetLinks:
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          weights:
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          technicalAttributes:
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
        - semanticRelationships:
          - relatedNode: http://example.com/aeiou
            description: description
          - relatedNode: http://example.com/aeiou
            description: description
          timerange:
            relativeTime: true
            universalTime: true
            end: 2000-01-23T04:56:07.000+00:00
            begin: 2000-01-23T04:56:07.000+00:00
          featureVector: null
          detectedBy: detectedBy
          name: name
          compositionRelationships:
          - relatedObject: null
            type: 6
          - relatedObject: null
            type: 6
          assetLinks:
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          weights:
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          technicalAttributes:
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
        similarity:
        - 2.8841622
        - 2.8841622
        currentNode:
          semanticRelationships:
          - relatedNode: http://example.com/aeiou
            description: description
          - relatedNode: http://example.com/aeiou
            description: description
          timerange:
            relativeTime: true
            universalTime: true
            end: 2000-01-23T04:56:07.000+00:00
            begin: 2000-01-23T04:56:07.000+00:00
          featureVector: null
          detectedBy: detectedBy
          name: name
          compositionRelationships:
          - relatedObject: null
            type: 6
          - relatedObject: null
            type: 6
          assetLinks:
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          weights:
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          technicalAttributes:
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
        generalMetadata:
          date: 2000-01-23T04:56:07.000+00:00
          fileName: fileName
          cityNearBy: cityNearBy
          previewUrl: http://example.com/aeiou
          iso: 3
          sourceSystem: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          latitude: 4
          resolution: 6
          shutterSpeed: 6
          aperture: 5.025005
          exposure: 9.965781
          fileSize: 6
          cameraModel: cameraModel
          width: 8
          lensModel: lensModel
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fileReference: ""
          longitude: 1
          focalLength: 9
          height: 9
        locations:
        - name: name
          location: http://example.com/aeiou
          type: 1
        - name: name
          location: http://example.com/aeiou
          type: 1
        collectionElements:
        - null
        - null
        end:
          relativeTime: true
          universalTime: true
          end: 2000-01-23T04:56:07.000+00:00
          begin: 2000-01-23T04:56:07.000+00:00
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        allNodes:
        - semanticRelationships:
          - relatedNode: http://example.com/aeiou
            description: description
          - relatedNode: http://example.com/aeiou
            description: description
          timerange:
            relativeTime: true
            universalTime: true
            end: 2000-01-23T04:56:07.000+00:00
            begin: 2000-01-23T04:56:07.000+00:00
          featureVector: null
          detectedBy: detectedBy
          name: name
          compositionRelationships:
          - relatedObject: null
            type: 6
          - relatedObject: null
            type: 6
          assetLinks:
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          weights:
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          technicalAttributes:
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
        - semanticRelationships:
          - relatedNode: http://example.com/aeiou
            description: description
          - relatedNode: http://example.com/aeiou
            description: description
          timerange:
            relativeTime: true
            universalTime: true
            end: 2000-01-23T04:56:07.000+00:00
            begin: 2000-01-23T04:56:07.000+00:00
          featureVector: null
          detectedBy: detectedBy
          name: name
          compositionRelationships:
          - relatedObject: null
            type: 6
          - relatedObject: null
            type: 6
          assetLinks:
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          - assetName: assetName
            location: http://example.com/aeiou
            type: 7
          weights:
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          - context:
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            weight: 0.8008282
          technicalAttributes:
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
          - blurryness: 7.0614014
            relative_x: 6
            relative_y: 1
            dominantColors:
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            - red: 9
              colorSpace:
                type: 7
                numComponents: 1
                cs_sRGB: true
              green: 3
              blue: 2
              alpha: 4
              transparency: 1
              rgb: 1
            width: 5
            sharpness: 2.302136
            height: 5
        begin:
          relativeTime: true
          universalTime: true
          end: 2000-01-23T04:56:07.000+00:00
          begin: 2000-01-23T04:56:07.000+00:00
        tempSimilarity:
        - 6.778325
        - 6.778325
      properties:
        nodes:
          items:
            $ref: '#/components/schemas/Node'
          type: array
        generalMetadata:
          $ref: '#/components/schemas/GeneralMetadata'
        security:
          $ref: '#/components/schemas/Security'
        locations:
          items:
            $ref: '#/components/schemas/Location'
          type: array
        currentNode:
          $ref: '#/components/schemas/Node'
        similarity:
          items:
            format: float
            type: number
          type: array
        tempSimilarity:
          items:
            format: float
            type: number
          type: array
        allNodes:
          items:
            $ref: '#/components/schemas/Node'
          type: array
        collectionElements:
          items:
            $ref: '#/components/schemas/MMFG'
          type: array
        id:
          format: uuid
          type: string
        begin:
          $ref: '#/components/schemas/Timerange'
        end:
          $ref: '#/components/schemas/Timerange'
      type: object
    Node:
      example:
        semanticRelationships:
        - relatedNode: http://example.com/aeiou
          description: description
        - relatedNode: http://example.com/aeiou
          description: description
        timerange:
          relativeTime: true
          universalTime: true
          end: 2000-01-23T04:56:07.000+00:00
          begin: 2000-01-23T04:56:07.000+00:00
        featureVector: null
        detectedBy: detectedBy
        name: name
        compositionRelationships:
        - relatedObject: null
          type: 6
        - relatedObject: null
          type: 6
        assetLinks:
        - assetName: assetName
          location: http://example.com/aeiou
          type: 7
        - assetName: assetName
          location: http://example.com/aeiou
          type: 7
        weights:
        - context:
            name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          weight: 0.8008282
        - context:
            name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          weight: 0.8008282
        technicalAttributes:
        - blurryness: 7.0614014
          relative_x: 6
          relative_y: 1
          dominantColors:
          - red: 9
            colorSpace:
              type: 7
              numComponents: 1
              cs_sRGB: true
            green: 3
            blue: 2
            alpha: 4
            transparency: 1
            rgb: 1
          - red: 9
            colorSpace:
              type: 7
              numComponents: 1
              cs_sRGB: true
            green: 3
            blue: 2
            alpha: 4
            transparency: 1
            rgb: 1
          width: 5
          sharpness: 2.302136
          height: 5
        - blurryness: 7.0614014
          relative_x: 6
          relative_y: 1
          dominantColors:
          - red: 9
            colorSpace:
              type: 7
              numComponents: 1
              cs_sRGB: true
            green: 3
            blue: 2
            alpha: 4
            transparency: 1
            rgb: 1
          - red: 9
            colorSpace:
              type: 7
              numComponents: 1
              cs_sRGB: true
            green: 3
            blue: 2
            alpha: 4
            transparency: 1
            rgb: 1
          width: 5
          sharpness: 2.302136
          height: 5
      properties:
        name:
          type: string
        weights:
          items:
            $ref: '#/components/schemas/Weight'
          type: array
        technicalAttributes:
          items:
            $ref: '#/components/schemas/TechnicalAttribute'
          type: array
        semanticRelationships:
          items:
            $ref: '#/components/schemas/SemanticRelationship'
          type: array
        compositionRelationships:
          items:
            $ref: '#/components/schemas/CompositionRelationship'
          type: array
        assetLinks:
          items:
            $ref: '#/components/schemas/AssetLink'
          type: array
        detectedBy:
          type: string
        timerange:
          $ref: '#/components/schemas/Timerange'
        featureVector:
          $ref: '#/components/schemas/MMFG'
      type: object
    Security:
      example:
        group_id: group_id
        owner_id: owner_id
        acl: acl
      properties:
        owner_id:
          type: string
        group_id:
          type: string
        acl:
          type: string
      type: object
    SemanticRelationship:
      example:
        relatedNode: http://example.com/aeiou
        description: description
      properties:
        relatedNode:
          format: url
          type: string
        description:
          type: string
      type: object
    TechnicalAttribute:
      example:
        blurryness: 7.0614014
        relative_x: 6
        relative_y: 1
        dominantColors:
        - red: 9
          colorSpace:
            type: 7
            numComponents: 1
            cs_sRGB: true
          green: 3
          blue: 2
          alpha: 4
          transparency: 1
          rgb: 1
        - red: 9
          colorSpace:
            type: 7
            numComponents: 1
            cs_sRGB: true
          green: 3
          blue: 2
          alpha: 4
          transparency: 1
          rgb: 1
        width: 5
        sharpness: 2.302136
        height: 5
      properties:
        relative_x:
          format: int32
          type: integer
        relative_y:
          format: int32
          type: integer
        width:
          format: int32
          type: integer
        height:
          format: int32
          type: integer
        sharpness:
          format: float
          type: number
        blurryness:
          format: float
          type: number
        dominantColors:
          items:
            $ref: '#/components/schemas/TechnicalAttribute_dominantColors_inner'
          type: array
      type: object
    Timerange:
      example:
        relativeTime: true
        universalTime: true
        end: 2000-01-23T04:56:07.000+00:00
        begin: 2000-01-23T04:56:07.000+00:00
      properties:
        begin:
          format: date-time
          type: string
        end:
          format: date-time
          type: string
        universalTime:
          type: boolean
        relativeTime:
          type: boolean
      type: object
    Weight:
      example:
        context:
          name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        weight: 0.8008282
      properties:
        context:
          $ref: '#/components/schemas/Context'
        weight:
          format: float
          type: number
      type: object
    GMAF:
      example:
        processingPlugins:
        - processingPlugins
        - processingPlugins
        plugins:
        - plugins
        - plugins
      properties:
        processingPlugins:
          items:
            type: string
          type: array
          writeOnly: true
        plugins:
          items:
            type: string
          type: array
      type: object
    GraphCode:
      properties:
        dictionary:
          items:
            type: string
          type: array
        collectionElements:
          items:
            $ref: '#/components/schemas/GraphCode'
          type: array
        relationships:
          items:
            items:
              format: int32
              type: integer
            type: array
          type: array
        collection:
          type: boolean
      type: object
    TechnicalAttribute_dominantColors_inner_colorSpace:
      example:
        type: 7
        numComponents: 1
        cs_sRGB: true
      properties:
        type:
          format: int32
          type: integer
        numComponents:
          format: int32
          type: integer
        cs_sRGB:
          type: boolean
      type: object
    TechnicalAttribute_dominantColors_inner:
      example:
        red: 9
        colorSpace:
          type: 7
          numComponents: 1
          cs_sRGB: true
        green: 3
        blue: 2
        alpha: 4
        transparency: 1
        rgb: 1
      properties:
        red:
          format: int32
          type: integer
        green:
          format: int32
          type: integer
        blue:
          format: int32
          type: integer
        alpha:
          format: int32
          type: integer
        colorSpace:
          $ref: '#/components/schemas/TechnicalAttribute_dominantColors_inner_colorSpace'
        rgb:
          format: int32
          type: integer
        transparency:
          format: int32
          type: integer
      type: object

